- id: gitSanity
  name: GitSanity
  description: This hook checks for potential hard-coded credentials.
  entry: gitSanity
  language: python
- id: decrypt
  name: Decrypt
  description: This hook checks for encrypted string and decrypts it using user provided key.
  entry: decrypt
  language: python
- id: gitSanityPush
  name: GitSanityPush
  description: This hook pushes commit then runs decrypt.
  entry: gitSanityPush
  language: python
